---
- name: Start nginx only if it's installed and stopped if not then install it
  hosts: workers
  become: yes

  tasks:
    - name: Check if nginx is installed
      shell: dpkg -l | grep nginx
      register: nginx_installed
      ignore_errors: yes

    - name: Install nginx if not installed
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: nginx_installed.rc != 0

    - name: Check if nginx is running
      shell: systemctl is-active nginx
      register: nginx_status
      ignore_errors: yes
      when: nginx_installed.rc == 0 or nginx_installed.rc is undefined

    - name: Start nginx if it's installed and not running
      service:
        name: nginx
        state: started
      when:
        - nginx_installed.rc == 0 or nginx_installed.rc is undefined
        - nginx_status.stdout != "active"
